language: python
matrix:
  include:
  - name: Python 3.7.x on Xenial Linux
    python: 3.7
    dist: xenial
  - name: Python 3.7.4 on macOS
    os: osx
    osx_image: xcode11
    language: shell
  - name: Python 3.7.4 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.4
    - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
- pip3 install -r requirements.txt
script:
- if [ $TRAVIS_OS_NAME == "linux" ];   then pyinstaller -F beatcounter.py -n beatcounter.appimage --add-data  beatcounter:beatcounter   ; fi
- if [ $TRAVIS_OS_NAME == "windows" ]; then pyinstaller -F beatcounter.py -n beatcounter.exe      --add-data 'beatcounter;beatcounter'  ; fi
- if [ $TRAVIS_OS_NAME == "osx" ];     then pyinstaller -F beatcounter.py -n beatcounter.dmg      --add-data  beatcounter:beatcounter   ; fi
after_script:
- find dist build
deploy:
  provider: releases
  api_key:
    secure: APWVqj/HyAk7dyKW91sbFNbFW9yRVxv+4zeHITDBUto1TtBXxP7Cz3b2dGz2AlIL5hpKiesVFAie9D/G3AEClxn4CD63/JYVAvKn+aJJNNF3N+LuQuxuBnpZycFu25/Rs98U3rMjS2lZpmSFTSazdEH6fy674vn40sPsRkCh3/BnCeGbR6ylntXbap/Ip57xhBZmKEEGo9TJAjYR9rAjmBo9v7ezrjNoRVFm0GpY5qpIS9A5bVANJMOnh+wV4B7NerhF55aTlQGLBErwGZ2emAO13PoWVJLu0ysxX++hyORK15UOzIKd2Ax0o13dcUFtAP4dbhQhD3wVAglTeU+RO3nZ/bcgQ2cRKhQ/i5YaBKPzCJ6mnqyrCXyG5HoEMyYq9B9LvI2B7j0XMVbFdgF3lL2aLtidgoeOBNsfkpJnF1EN51NZQNKo4lKaBICRRwCY/xFh9QdBqEpu3drbWFzSlVslZpP0hCsKXhF3bVJBQMUoZXOQwOqHygss7vPJRchBbBktmonG1oxtz25DGCsLhM0lMYWi4tPL6hjKdXYum/620DMlisLO3YUEFDv44Hxk+YXlM4/z366DDlICDoBHHjgJ+RJrZcj7Gtw2DeY3lr0FnABDOnjQoyrG+O5vKQuyW9nJEn8bIgzvQYydfm2vwksZ9njEFtKrHDjXV5L2coA=
  file_glob: true
  file: dist/*
  overwrite: true
  skip_cleanup: true
